name: Build PR Content

# Runs on both same-repo PRs and fork PRs - NO SECRETS
# Fork PRs will build but upload will be blocked
on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]  # Also run when PRs are merged to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # For pull_request_target: checkout the PR code (head)
          # For pull_request: use PR head SHA
          # For push: use default SHA
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          # For pull_request_target, we need to fetch the PR head
          fetch-depth: 0

      # Your build steps here (example)
      - name: Build
        run: |
          # npm install
          # npm run build
          # or whatever builds your content
          mkdir -p dist
          echo "Built content" > dist/index.html

      # Use the action in BUILD mode (default, no secrets needed)
      # The action automatically saves PR metadata and generates artifact names
      - name: Build CAR file
        id: build
        uses: sgtpooki/filecoin-upload-action@v1
        with:
          # mode: build is the default, but can be specified explicitly
          path: dist
