name: Validate Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    name: Validate YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: action.yml examples/
          format: github
          strict: true
          # .yamllint config file is automatically used

      - name: Validate action can be loaded
        uses: ./
        id: test-load
        with:
          path: .
          # mode: build is default, doesn't need secrets

      - name: Verify action loaded successfully
        run: echo "✅ Action metadata is valid and loaded successfully"

